MatchStats/MatchStats/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("main.urls")),
    path("accounts/", include("user.urls")),
    path('admin/', admin.site.urls),
]

MatchStats/main/urls.py
from django.urls import path

from . import views
from .apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("teams/", views.TeamsList.as_view(), name = "team_list"),
    path("team/<int:pk>/", views.TeamDetail.as_view(), name="team_detail"),
    path("match/<int:pk>/", views.MatchDetail.as_view(), name="match_detail"),
    path('player/<int:pk>/', views.PlayerDetail.as_view(), name='player_detail'),
    path("transfer/<int:pk>/", views.TransferDetail.as_view(), name="transfer_detail"),
    path("matches/", views.MatchList.as_view(), name="match_list"),
    path("stadiums/", views.StadiumList.as_view(), name="stadium_list"),
    path('players/',views.PlayersList.as_view(),name="player_list"),
    path('transfers/', views.TransferList.as_view(), name="transfer_list"),
    path('transfers/<int:user_id>/', views.TransferFilteredList.as_view(), name="transfer_list"),
    path('player/<int:pk>/update/',views.PlayerUpdateView.as_view(), name="player_update"),
    path('team/<int:pk>/update/',views.TeamUpdateView.as_view(), name="team_update"),
    path('match/<int:pk>/update',views.MatchUpdateView.as_view(), name="match_update"),
    path('table/',views.PointsTable.as_view(), name="points_table"),
]

MatchStats/main/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

class Stadium(models.Model):
    name = models.CharField(max_length=128, unique=True)
    address = models.CharField(max_length=512)
    city = models.CharField(max_length=64)
    capacity = models.PositiveIntegerField()

    def __str__(self):
        return self.name

class Team(models.Model):
    name = models.CharField(max_length=128, unique=True)
    code = models.CharField(max_length=3, unique=True)
    stadium = models.ForeignKey(Stadium, on_delete=models.SET_NULL, null=True, blank=True)
    played = models.PositiveSmallIntegerField(default=0)
    wins = models.PositiveSmallIntegerField(default=0)
    draws = models.PositiveSmallIntegerField(default=0)
    losses = models.PositiveSmallIntegerField(default=0)
    goals_for = models.PositiveSmallIntegerField(default=0)
    goals_against = models.PositiveSmallIntegerField(default=0)
    points = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name


class Player(models.Model):
    POSITION = [
        ('G',"Goalkeeper"),
        ('D',"Defender"),
        ('M',"Midfielder"),
        ('F',"Forward"),
    ]

    name = models.CharField(max_length=128)
    team = models.ForeignKey(Team, null=True, blank=True, on_delete = models.SET_NULL)
    jersey_no = models.PositiveSmallIntegerField(null=True)
    dob = models.DateField()
    position = models.CharField(max_length=1, choices=POSITION)
    goals = models.PositiveSmallIntegerField(default=0)
    assists = models.PositiveSmallIntegerField(default=0)
    yellow_cards = models.PositiveSmallIntegerField(default=0)
    red_cards = models.PositiveSmallIntegerField(default=0)
    nationality = models.CharField(max_length=64)
    height = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.name

class Match(models.Model):
    team_1 = models.ForeignKey(Team, null=True, related_name="team_1", on_delete=models.SET_NULL)
    team_2 = models.ForeignKey(Team, null=True, related_name="team_2", on_delete=models.SET_NULL)
    score_1 = models.PositiveSmallIntegerField(default=0)
    score_2 = models.PositiveSmallIntegerField(default=0)
    shots_1 = models.PositiveSmallIntegerField(default=0)
    shots_2 = models.PositiveSmallIntegerField(default=0)
    offsides_1 = models.PositiveSmallIntegerField(default=0)
    offsides_2 = models.PositiveSmallIntegerField(default=0)
    corners_1 = models.PositiveSmallIntegerField(default=0)
    corners_2 = models.PositiveSmallIntegerField(default=0)
    match_time = models.DateTimeField()
    completed = models.BooleanField(default=False)
    stadium = models.ForeignKey(Stadium, null=True, on_delete=models.SET_NULL)
    viewer_count = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.team_1.code + " vs " + self.team_2.code

class Transfer(models.Model):
    team_from = models.ForeignKey(Team, null=True, related_name="team_from", blank=True, on_delete=models.SET_NULL)
    team_to = models.ForeignKey(Team, null=True, related_name="team_to", blank=True, on_delete=models.SET_NULL)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    price = models.FloatField(validators=[MinValueValidator(0.0)])
    transfer_date = models.DateField()

class Staff(models.Model):
    STAFF_JOB_LIST = [
        ('tstaff', 'Tournament Staff'),
        ('mgr', 'Manager'),
        ('staff', 'Staff')
    ]
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    type = models.CharField(choices=STAFF_JOB_LIST, max_length=20)
    team_id = models.ForeignKey(Team, null=True, blank=True, on_delete=models.SET_NULL)

class Goal(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, null=True, on_delete = models.SET_NULL)
    scorer = models.ForeignKey(Player, null=True, related_name="goal_set", on_delete=models.SET_NULL)
    assister = models.ForeignKey(Player, null=True, related_name="assist_set",blank=True, on_delete=models.SET_NULL)
    match_time = models.PositiveSmallIntegerField(validators=[MaxValueValidator(120)])

MatchStats/main/views.py
from django.urls import reverse
from django.views import generic
from django.urls import reverse_lazy
from .models import Stadium, Player, Team, Match, Transfer, Staff
from django.contrib.auth.models import User

class IndexView(generic.TemplateView):
    template_name = "main/index.html"

class TeamsList(generic.ListView):
    model = Team
    template_name = 'main/team_list.html'
    context_object_name = "teams"
    ordering = ["name"]

class PointsTable(generic.ListView):
    model = Team
    template_name = 'main/points_table.html'
    context_object_name = "teams"
    ordering = ["-points"]

class TeamDetail(generic.DetailView):
    model = Team
    template_name = 'main/team_detail.html'

class StadiumList(generic.ListView):
    model = Stadium
    template_name = 'main/stadium_list.html'
    context_object_name = "stadiums"

class MatchList(generic.ListView):
    model = Match
    template_name = 'main/match_list.html'
    context_object_name = "matches"
    ordering = ["match_time"]

class MatchDetail(generic.DetailView):
    model = Match
    template_name = 'main/match_detail.html'

class PlayerDetail(generic.DetailView):
    model = Player
    template_name = 'main/player_detail.html'

class PlayersList(generic.ListView):
    model = Player
    template_name = 'main/player_list.html'
    context_object_name = "players"
    ordering = ['name']

class TransferList(generic.ListView):
    model = Transfer
    template_name = "main/transfer_list.html"
    context_object_name = "transfers"
    ordering = ['-transfer_date']

class TransferFilteredList(generic.ListView):
    model = Transfer
    template_name = "main/transfer_list.html"
    context_object_name = "transfers"
    ordering = ['-transfer_date']

    def get_queryset(self):
        qs = super().get_queryset()
        user  = User.objects.get(pk=self.kwargs['user_id'])
        if user.username == 'admin':
            return qs
        elif not Staff.objects.filter(user_id=user):
            return None
        team = user.staff.team_id
        return qs.filter(team_from=team) | qs.filter(team_to=team)

class TransferDetail(generic.DetailView):
    model = Transfer
    template_name = "main/transfer_detail.html"

class TeamUpdateView(generic.UpdateView):
    model=Team
    fields = '__all__'
    template_name = 'main/team_update.html'
    def get_success_url(self):
        return reverse('main:team_detail', kwargs={'pk' : self.object.pk})
      

class PlayerUpdateView(generic.UpdateView):
    model = Player
    fields = ['name','team','jersey_no','dob','position','goals','assists','yellow_cards','red_cards','nationality','height']
    template_name = 'main/player_update.html'
    def get_success_url(self):
        return reverse('main:player_detail', kwargs={'pk' : self.object.pk})
      

class MatchUpdateView(generic.UpdateView):
    model = Match
    fields = '__all__'
    template_name = 'main/match_update.html'
    def get_success_url(self):
        return reverse('main:match_detail', kwargs={'pk' : self.object.pk})
      
   

MatchStats/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}MatchStats{% endblock %}

{% block content %}
<style>
  body, html {
    height: 100vh;
    margin: 0;
    padding: 0;
  }

  #intro {
    background-image: url("../../static/img/ball.jpg");
    background-size: cover;
    background-position: center;
    height: 100vh; 
    display: flex;
    align-items: center;
    justify-content: center;
   
  }

  .mask {
    background-color: rgba(0, 0, 0, 0.8);
    border-radius: 10px; 
  }

  .nav-link {
    color: white;
    text-decoration: none;
    display: inline-block;
    padding: 10px;
    transition: background-color 0.3s, text-decoration 0.3s;
  }

  .nav-link:hover {
    background-color: rgba(255, 255, 255, 0.3);
    text-decoration: underline;
    border-radius: 10px; 
  }
  #text {
    width: 70vw;
    height: 60vh;
    margin: 0 auto;
  }
  .title{
    text-transform: uppercase;
    letter-spacing: 1rem;
    font-size: 5rem;
  }

</style>
<link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
<main>
  <div id="intro" class="bg-image shadow-2-strong ">
    <div class="mask">
      <div  id='text'class="container-fluid d-flex flex-column items-center justify-content-center ">
        <div class="text-white text-center ">
            <h1 class="mb-3 title">MatchStats</h1>
            {% if not user.is_authenticated %}
            <a class="btn btn-primary text-white" href="{% url 'user:login' %}" role="button"
                rel="nofollow">Login</a>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

MatchStats/main/templates/main/match_detail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title%}{{ match }}{% endblock %}

{% block content%}

<style>
    body {
    background-color: #f5f5f5;
    font-family: Arial, sans-serif;
    overflow: visible;
    
  }
  
</style>

  <header style =" height : 300px">
    <h1> {{match.team_1}}</h1>
    <div><h1 class="display-1">{{match.score_1}}</h1></div>
    <h1 class="display-1"> - </h1>
    <div><h1 class="display-1">{{match.score_2}}</h1></div>
    <h1>{{match.team_2}}</h1>
  </header>

<div class="card text-center" style="color:rgb(22, 22, 149); background-color: rgb(185, 236, 255);">
  <div class="card-body">
    <h5 class="display-6 card-title">{{match.stadium}}</h5>
    <h6 class=" card-text"> {{match.match_time}}</h6>
  </div>
</div>

<hr>
{% if match.completed %}
  <div class="container text-center">
    <div class="row align-items-end">
      <div class="col">
        <h3>{{ match.shots_1 }}</h3>
      </div>
      <div class="col">
        <h2>Shots</h2>
      </div>
      <div class="col">
        <h3>{{ match.shots_2 }}</h3>
      </div>
    </div>
  </div>
  <hr>
  <div class="container text-center">
    <div class="row align-items-end">
      <div class="col">
        <h3>{{ match.offsides_1 }}</h3>
      </div>
      <div class="col">
        <h2>Offsides</h2>
      </div>
      <div class="col">
        <h3>{{ match.offsides_2 }}</h3>
      </div>
    </div>
  </div>
  <hr>
  <div class="container text-center">
    <div class="row align-items-end">
      <div class="col">
        <h3>{{ match.corners_1 }}</h3>
      </div>
      <div class="col">
        <h2>Corners</h2>
      </div>
      <div class="col">
        <h3>{{ match.corners_2 }}</h3>
      </div>
    </div>
  </div>
  <hr>
  {% else %}
    <h1>Match is yet to start</h1>
 {% endif %}


{% endblock %}

MatchStats/main/templates/main/match_list.html
{% extends 'main/base.html' %}
{% block title %}Match List{% endblock %}

{% block content %}
<style>
    body {
        background-color: #f2f6fa;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        overflow: visible;
    }

    .container {
        text-align: center;
    }

    h1 {
        font-size: 4rem;
        color: #0a0244;
        margin-bottom: 30px;
        padding: 10px;
        display: inline-block;
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        border-radius: 10px;
        text-transform: uppercase;
        letter-spacing: 20px;
        text-align: center;
    }

    .match-card {
        background-color: #1c3648;
        padding: 20px;
        margin-bottom: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s ease-in-out;
        color: #ffffff;
    }

    .match-card:hover {
        transform: translateY(-5px);
    }

    .team-names {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .match-details {
        display: flex;
        justify-content: space-between;
        font-size: 16px;
    }

    .completed {
        color: #000000;
        background-color: #28a745;
        padding: 4px 8px;
        border-radius: 4px;
    }

    .not-completed {
        color: #ffffff;
        background-color: #dc3545;
        padding: 4px 8px;
        border-radius: 4px;
    }

    .match-link {
        text-decoration: none;
    }
</style>

    <div class="container">
        <h1>Matches</h1>
        <div class="row">
            {% for match in matches %}
            <div class="col-md-6">
              <a href="{% url 'main:match_detail' match.id %}" class="match-link">
                <div class="match-card">
                  <div class="team-names">
                    {{ match.team_1.code }} {{ match.score_1 }} - {{ match.score_2 }} {{ match.team_2.code }}
                  </div>
                  <div class="match-details">
                    <span>{{ match.match_time }}</span>
                    <span class="{% if match.completed %}completed{% else %}not-completed{% endif %}">
                      {% if match.completed %}Completed{% else %}Not Completed{% endif %}
                    </span>
                  </div>
                </div>
              </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

MatchStats/main/templates/main/match_update.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Update Match{% endblock %}


{% block content %}
<style>
    form{
        width: 50%;
        align-items: center;
        margin-left: 25%;
    }
</style>
<header>
    <h1 class="display-1" style="width: 100%;">Update Match</h1>
</header>
<br>
<form method="post" action="{% url 'main:match_update' match.id %}" >
    {% csrf_token %}
    {{form.as_p}}
    
    <input type="submit" value="Update"  class="btn btn-primary"> 
    <button type="reset" class="btn btn-danger"> Reset </button>
    <a href="{% url 'main:match_detail' match.id %}" class="btn btn-primary"> Cancel </a>

</form>
{% endblock %}

MatchStats/main/templates/main/player_detail.html
{% extends 'main/base.html' %}
{load static}
{% block title %}Player Detail{% endblock %}

{% block content %}
<style>

  
  body {
    background-color: #f5f5f5;
    font-family: Arial, sans-serif;
    overflow: visible;
    
  }
  
  h1 {
    /* font-size: 32px; */
    text-transform: uppercase;
    font-weight: 400;
    margin-bottom: 20px;
    text-align: center;
  }
  
  .grid-container {
    display: grid;
    grid-template-columns: 30% 1fr;
    grid-gap: 20px;
  }
  
  .name-box {
    background-image: linear-gradient(to right, red, yellow, rgb(61, 243, 61));
    color: #fff;
    padding: 10px;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  .details-box {
    background-color: #fff;
    color: #333;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }
  
  .details-box h4 {
    margin-bottom: 20px;
  }
  
  .red-card-box {
    background-color: rgba(248, 1, 1, 0.685);
    color: #fff;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
   
  }
  
  .yellow-card-box {
    background-color: yellow;
    color: #000;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }
  
  .container {
    max-width: 800px;
    margin: 0 auto;
  }
  
  .cards {
    align-items: center;
    margin-top: 20px;
  }
  
  .cards h4 {
    margin-right: 10px;
  }
  
  .cards .red-card-box,
  .cards .yellow-card-box {
    margin: 0 10px;
    width: 60px;
  }
</style>

<div class="container text-center mt-3 pt-3"
style="background-color: rgb(156, 175, 228);  border-radius: 10px;">
    <h1 class="display-4" style="display: inline-block; color: rgb(4, 4, 61); font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif ;">{{ player.name }}</h1>
</div>

<body>
    <!-- <div class="grid-container">
        <div class="name-box">
            <h1><strong>{{ player.name }}</strong></h1>
        </div>
         -->
         <div class="container text-center my-5" >
         
         <h1 style="font-family: Georgia, 'Times New Roman', Times, serif; color: rgb(35, 5, 66);">{{ player.team.name }}</h1>
            <hr>
        <h4>Jersey No:{{player.jersey_no}}</h4> 
        <hr>   
        {% if player.position == "G" %}
        <h4>Position: Goal Keeper</h4>
        {% elif player.position == "M" %}
        <h4>Position: Mid Fielder</h4>
        {% elif player.position == "F" %}
        <h4>Position: Forward</h4>
        {% else %}
        <h4>Position: Defender</h4>
        {% endif %}
        <hr>
        <h4>Goals Scored: {{ player.goals }}</h4>
        <hr>
        <h4>Assists Given : {{ player.assists }}</h4>
        <hr>
        <h4>Country: {{ player.nationality }}</h4>
        <hr>
        <h4>DOB: {{ player.dob }}</h4>
        <hr>
        <h4>Height: {{ player.height }} cm</h4>
        <hr>
            <div class="cards row d-flex justify-content-center items-center" style="display: block ;width: 100%" align="center">
                <div class="yellow-card-box my-3" style="width:60px">
                    <h6>{{ player.yellow_cards }}</h6>
                </div>
                <div class="red-card-box my-3">
                    <h6> {{ player.red_cards }}</h6>
                </div>
            </div>
        <hr>
    </div>
</div>
</body>

{% endblock %}

MatchStats/main/templates/main/player_list.html
{% extends 'main/base.html' %}

{% block title %}PLAYERS{% endblock %}

{% block content %}
<style>
    body {
    background-color: #f5f5f5;
    font-family: Arial, sans-serif;
    overflow: visible;
    
  }
  
    .container {
        background-color: #f2f6fa;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        overflow: visible;
        margin-top: 30px;
    }
    h1 {
        font-size: 4rem;
        color: #007ACC;
        margin-bottom: 30px;
        padding: 10px;
        display: inline-block;
        text-align: center;
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        border-radius: 10px;
        text-transform: uppercase;
        letter-spacing: 20px;
        
    }

    .player-card {
        background-color: #080049;
        padding: 20px;
        margin-bottom: 20px;
        border-radius: 10px;
        /* box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); */
        transition: transform 0.2s ease-in-out;
    }

    .player-card:hover {
        transform: translateY(-5px);
    }

    .player-name {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
        color: #b969a2;
        text-align: center;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .player-details {
        font-size: 14px;
        color: #ffffff;
        text-align: center;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .player-details span {
        display: block;
        margin-bottom: 5px;
    }
</style>

<div class="container">
    <h1    >PLAYERS</h1>
    <div class="row">
        {% for player in players %}
        <div class="col-md-4">
            <a href="{% url 'main:player_detail' player.id %}" style="text-decoration: none;">
                <div class="player-card">
                    <div class="player-name">
                        {{ player.name }}
                    </div>
                    <div class="player-details">
                        <span><strong>Team:</strong> {{ player.team }}</span>
                        {% if player.position == "G" %}
                        <p>Position: Goal Keeper</p>
                        {% elif player.position == "M" %}
                        <p>Position: Mid Fielder</p>
                        {% elif player.position == "F" %}
                        <p>Position: Forward</p>
                        {% else %}
                        <p>Position: Defender</p>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

MatchStats/main/templates/main/player_update.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Update Team{% endblock %}


{% block content %}
<style>
    form{
        width: 50%;
        align-items: center;
        margin-left: 25%;
    }
</style>
<header>
    <h1 class="display-1" style="width: 100%;">Update Player</h1>
</header>
<br>
<form method="post" action="{% url 'main:player_update' player.id %}" >
    {% csrf_token %}
    {{form.as_p}}
    
    <input type="submit" value="Update"  class="btn btn-primary"> 
    <button type="reset" class="btn btn-danger"> Reset </button>
    <a href="{% url 'main:player_detail' player.id %}" class="btn btn-primary"> Cancel </a>

</form>
{% endblock %}

MatchStats/main/templates/main/points_table.html
{% extends 'main/base.html' %}

{% block title%}Teams{% endblock %}

{% block content%}
<style>
   .change_color:hover{
        background-color: rgb(39, 141, 48);
    }
</style>
<div class="container my-5">
<table class="table">
    <thead>
      <tr style="background-color: rgba(30, 30, 150, 0.788); color: white;">
        <th scope="col">#</th>
        <th scope="col">Club</th>
        <th scope="col">Matches Played</th>
        <th scope="col">Wins</th>
        <th scope="col">Draws</th>
        <th scope="col">Losses</th>
        <th scope="col">Goals Scored</th>
        <th scope="col">Goals Conceded</th>
        <th scope="col">Points</th>
      </tr>
    </thead>
    <tbody>
    {% for team in teams %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="change_color" href="{% url 'main:team_detail' team.id %}"  style="text-decoration: none; color: rgb(8, 8, 8);" >{{ team.name }}</a></td>
        <td>{{ team.played }}</td>
        <td>{{ team.wins }}</td>
        <td>{{ team.draws }}</td>
        <td>{{ team.losses }}</td>
        <td>{{ team.goals_for }}</td>
        <td>{{ team.goals_against }}</td>
        
        <!-- <td>{%{ team.goals_for - team.goals_against }}</td> -->
        <td>{{ team.points }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

MatchStats/main/templates/main/team_detail.html
{% extends 'main/base.html' %}

{% block title%}{{ team.name }}{% endblock %}

{% block content %}
<style>
    body {
        background-color: #f2f6fa;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        overflow: visible;
    }

    .container {
        margin-top: 30px;
    }

    .player-card {
        background-color: #080049;
        padding: 20px;
        margin-bottom: 20px;
        border-radius: 10px;
        /* box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); */
        transition: transform 0.2s ease-in-out;
    }

    .player-card:hover {
        transform: translateY(-5px);
    }

    .player-name {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
        color: #b969a2;
        text-align: center;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .player-details {
        font-size: 16px;
        color: #ffffff;
        text-align: center;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .player-details span {
        display: block;
        margin-bottom: 5px;
    }
</style>
<div class="text-center">
    <h1>{{ team.name }}</h1>

<div class="container">
    <h1 style="text-align: center; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 32px; color: #007ACC; margin-bottom: 30px;">Player List</h1>
    <div class="row">
        {% for player in team.player_set.all %}
        <div class="col-md-4">
            <a href="/player/{{ player.id }}" style="text-decoration: none;">
                <div class="player-card">
                    <div class="player-name">
                        {{ player.name }}
                    </div>
                    <div class="player-details">
                        <!-- <span><strong>Team:</strong> {{ player.team }}</span> -->
                        {% if player.position == "G" %}
            <p>Position: Goal Keeper</p>
            {% elif player.position == "M" %}
            <p>Position: Mid Fielder</p>
            {% elif player.position == "F" %}
            <p>Position: Forward</p>
            {% else %}
            <p>Position: Defender</p>
            {% endif %}
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </ul>
    <div align="right"><button class = "btn btn-primary"><a href="{% url 'main:team_update' team.id %}" style = "color: aliceblue;text-decoration: none;">Edit</a></button></div>
</div>
{%endblock%}

MatchStats/main/templates/main/team_update.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Update Team{% endblock %}


{% block content %}
<style>
    form{
        width: 50%;
        align-items: center;
        margin-left: 25%;
    }
</style>
<header>
    <h1 class="display-1" style="width: 100%;">Update Team</h1>
</header>
<br>
<form method="post" action="{% url 'main:team_update' team.id %}" >
    {% csrf_token %}
    {{form.as_p}}
    
    <input type="submit" value="Update"  class="btn btn-primary"> 
    <button type="reset" class="btn btn-danger"> Reset </button>
    <a href="{% url 'main:team_detail' team.id %}" class="btn btn-primary"> Cancel </a>

</form>
{% endblock %}

MatchStats/main/templates/main/transfer_detail.html
{% extends 'main/base.html' %}

{% block title%}{{ team.name }}{% endblock %}

{% block content%}
<style>
   .players{
        width: 100%;
        background-color: rgb(173, 233, 214);
        margin-bottom:2px;
        font-size: large;
        text-align: center;
        list-style-type: none;
        padding: 2px;;

    }
    
   .change_color:hover{
        background-color: rgb(250, 215, 244);
    }

</style>
<div class="text-center">
    <h1>{{ transfer.player }}</h1>
    <div class="fs-3">
        <p>{{ transfer.team_from }} -> {{ transfer.team_to }}</p>
        <p>Price: ${{ transfer.price }}</p>
        <p>Date: ${{ transfer.transfer_date }}</p>
    </div>    
</div>
{%endblock%}